name: Publish Extension
on:
  push:
   branches:
    - master
   paths-ignore:
    - 'README.md'
    - '.github/workflows/**'
    - 'package-lock.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - name: npm install
      run: npm install
    - name: install vsce globaly
      run: npm install -g vsce
    - name: packag extension
      run: vsce package
    - name: publish extension
      run: vsce publish -p ${{secrets.VSCE_TOKEN}}
